- README.md
- src/anndata_to_bq.py
- src/initialize_dataset.py
Only one change was actually required to be able to ingest 1 M cells, specifying `copy=False` in the `.tocoo` invocation on the raw data matrix. Likely this sidesteps a default defensive copy which becomes very expensive at this scale.
Also this only took about an hour total so it's already quite performant on a pretty large dataset. I made an attempt at using Avro but execution actually got 5x slower so I backed away from that. It's possibly I did something dumb as that was my first time Avroing, but given how performant the TSV version of this code is already I'm not sure trying again with Avro is the best use of resources in the CAS development space right now. 🙂
> Skip expensive copy on COO conversion for scalability [VS-506]

- README.md
- requirements.txt
- src/anndata_to_avro.py
- src/anndata_to_bq.py
- src/load_dataset.py
Despite what the diffs say the two Python files here are not new, they're just heavily revised and renamed. `anndata_to_avro.py` now writes Avro  instead of TSV. h/t `fastavro` for making this Avro export run ~2x faster than TSV export. The loading process has also been streamlined to tack the actual loading of BQ tables onto the dataset and table creation process, so now there are only two steps:
```
$ python src/load_dataset.py --project gvs-internal --dataset retinal_all_major --avro_prefix retinal_all_major --gcs_prefix gs://gvs-internal-space/scratch
Created dataset gvs-internal.Dataset(DatasetReference('gvs-internal', 'retinal_all_major')).
Created 'gvs-internal.retinal_all_major.cas_cell_info'.
Created 'gvs-internal.retinal_all_major.cas_feature_info'.
Created …
```
> Write Avro, rewrite loader [VS-510]

- src/anndata_to_avro.py
- src/load_dataset.py
The Avro writer now assigns an MD5-driven ingest id to cells and features. We can use this ingest id to know which features were assayed for a particular cell. The loader also uses this ingest id to create an ingest record or defend against accidental re-ingests if such a record already exists.
> Record ingest event and associate cells and features [VS-535]

- src/casp/anndata_to_avro.py
- src/casp/load_dataset.py
Per discussion with Google, the previous situation of being unable to load JSON columns from Avro files is a bug which Google was aware of and for which a fix is currently being rolled out. The fix is expected to become generally available in one to two weeks, but in the meantime projects must be put on an "allow list" in order for JSON column loading from Avro files to work. Our `gvs-internal` project has been allowlisted so this code works fine there, but `broad-dsp-spec-ops` has not been allowlisted so this code does not work there.
> Use JSON columns for metadata [VS-546]

- src/casp/api/server.py
Calculate additional summary stats and updated output JSON format.  For example:
```
{
"query_cell_id": "99759",
"matches": [
{
"cell_type": "erythrocyte",
"cell_count": 94,
"min_distance": 1589.847900390625,
"p25_distance": 1664.875244140625,
"median_distance": 1791.372802734375,
"p75_distance": 1801.3585205078125,
"max_distance": 1840.047119140625
},
{
"cell_type": "monocyte",
"cell_count": 3,
"min_distance": 1716.2490234375,
"p25_distance": 1716.2490234375,
"median_distance": 1804.897216796875,
"p75_distance": 1841.0843505859375,
"max_distance": 1841.0843505859375
},
{
"cell_type": "erythroid progenitor cell",
"cell_count": 3,
"min_distance": 1462.53955078125,
"p25_distance": 1462.53955078125,
"median_distance": 1693.428955078125,
"p75_distance": 1788.7325439453125,
"max_distance": …
```
> include match summary stats, updated output JSON

- src/casp/services/_settings.py
- src/casp/services/api/README.md
- src/casp/services/db/__init__.py
- src/casp/services/model_inference/README.md
To allow larger throughput in the system, we need a larger DB connection Pool size. This is the current database connection overload on large datasets.
Possible solutions to increase throughput:
1. Implement caching (good for large-scale apps, CAS doesn't look like the one so far).
2. Aggregate write requests. A new issue for this (#110)
3. Increasing database SQL server machine requirements (number of CPUs, RAM). Already did it. In the cloud
4. Increase Database [connection pool](https://en.wikipedia.org/wiki/Connection_pool) size
It seems that neither RAM or CPUs are utilized well, while the number of maximum connections is reaching its limits which (imho) means that the database could easily afford an increase in connection pool size.
> DB connection pool size increase

- README.md
- setup.py
The repo has a dependency on Cellarium.ML which currently [requires python 3.10](https://github.com/cellarium-ai/cellarium-ml/blob/55a902cca9945cadef90d2300f2f7b9258b921e2/pyproject.toml#L13).  Additionally, Cell Ranger is on 3.10 and for a variety of reasons having one python version makes life easier.
> Enforce Python >= 3.10

- src/casp/data_manager/base_data_manager.py
- src/casp/services/_auth/jwt_token.py
- src/casp/services/admin/__init__.py
- src/casp/services/admin/views.py
- src/casp/services/api/data_manager/cellarium_general.py
- src/casp/services/api/services/cell_operations_service.py
- src/casp/services/db/__init__.py
- src/casp/services/db/migrations/env.py
- src/casp/services/db/migrations/versions/t_2024-03-27_17-00-17_user_activity.py
- src/casp/services/db/models.py
- src/casp/services/db/ops.py
- src/casp/services/model_inference/data_managers.py
- tests/unit/test_cell_operations_service.py
Changes in this PR:
- Added a new table, user_activity, which keeps track of cell_count for each user annotation request, along with some metadata about the request.
- Now using the sqlalchemy `with session.begin():` syntax for any insert and update operations into the DB for transactions
- Creating sessions from the session maker for logically-grouped database operations
- I might have overdone it here.  I think it makes sense to not just have the one session, but I wonder if maybe it would be better to have one session per request or something.
To do:
- Need to update the admin interface to display the proper counts for cells processed and requests processed on the user page
> Tracking user requests and cells processed in separate user activity table

- docs/source/modules/running_locally.rst
- docs/source/modules/secrets.rst
- src/casp/services/_settings.py
- src/casp/services/admin/README.rst
- src/casp/services/db/__init__.py
- src/casp/services/db/migrations/env.py
- src/casp/services/model_inference/README.rst
This PR adds the ability to connect to cloud sql postgres using its private IP, which is over our VPC.  That's needed if we want to run the model and admin services behind the VPC (which we do)
This functionality is enabled when the `DB_PRIVATE_IP` field is specified
This also documents how to connect to the services when they are not exposed to the internet.
My deployments are configured with this so you can check out how it works there.
> CAS-25 Support communicating with postgres over VPC

- .github/actions/docker-deploy/action.yml
- .github/workflows/deploy-workflow.yml
- requirements.txt
- src/casp/services/README.rst
- src/casp/services/admin/README.rst
- src/casp/services/api/README.rst
- src/casp/services/deploy/cloudrun/README.rst
- src/casp/services/deploy/cloudrun/default.json
- src/casp/services/deploy/cloudrun/large.json
- src/casp/services/logging.py
- src/casp/services/model_inference/README.rst
- src/casp/services/utils/email_utils.py
This PR adds a brand new GitHub workflow + action that will let us deploy the built docker image to CAS services via github.
Once merged, it will be doable from the UI but until then, this can be run via the github CLI using:
```
GIT_REF=<branch, git commit, tag, etc.> # Git reference to deploy the image from (helpful if modifying the deploy scripts or configuration files)
IMAGE_TAG=<docker tag> # Tag to deploy the docker image from.
SERVICE_ACCOUNT=sa-user@<project>.iam.gserviceaccount.com # Service account that will be running the service
SECRET_REF=secret-name:latest # Reference to secret in the project's google secret manager as <secret name>:<version or latest> (note that the service account must have access to the secret)
DB_CONNECTION=example-project:us-region-example:db-cluster-nam …
```
> CAS-25 Deploy CAS from GitHub Action

- src/casp/services/db/migrations/versions/t_2024-05-16_09-49-58_user_keys.py
After merging our previous PRs, our migrations had two "heads," which was caused by having the same reference in 2 latest migrations, preventing automatic migration application. This PR fixes it.
> Fix: DB multiple head revision

- .github/actions/docker-deploy/action.yml
Because you can't have uppercase labels in google deployments apparently
> Lower case the deployment labels

- src/casp/services/_settings.py
- src/casp/services/admin/__init__.py
- src/casp/services/admin/views.py
- src/casp/services/api/clients/model_client.py
- src/casp/services/api/data_manager/cellarium_general.py
- src/casp/services/api/routers/cellarium_general_router.py
- src/casp/services/api/schemas/cellarium_general.py
- src/casp/services/api/services/cellarium_general_service.py
- src/casp/services/app.py
- src/casp/services/constants.py
- src/casp/services/db/migrations/versions/t_2024-05-16_09-49-58_user_keys.py
- src/casp/services/db/migrations/versions/t_2024-06-04_18-55-57_user_feedback.py
- src/casp/services/db/models/users.py
- src/casp/services/deploy/cloudrun/default.json
- src/casp/services/logging.py
In service of collecting feedback from users:
- Adds support for passing `x-client-session-id` (separate PR coming for the client repo) from the client to group operations together on the back end for support/feedback ability which will track the overall client session
- Adds support for passing the `x-client-action-id` (separate PR coming for the client repo) from the client to group operations together on the back end for support/feedback ability which will track requests for a given action
- Add support for going to a feedback form:
- users will hit the `/feedback/answer?client_session_id&client_action_id` endpoint which will redirect to a form url with the client_session_id and client_action_id to track the user
- Add support for opting out of us asking for feedback
- Drive by: small …
> CAS-6 Make it possible to gather feedback from users

- src/casp/services/db/migrations/versions/t_2024-06-18_13-18-48_make_deployed_index_id_nullable.py
- src/casp/services/db/models/ml_management.py
We need to store undeployed indexes to keep the costs lower, but we still want them to be stored in the database for benchmarking.
> Feat: #129 Make index_deployed_id optional

- src/casp/services/admin/views.py
Pretty simple PR.  Just removes the bit of code that flashes the user's key on creation. Leaving most of the css etc. since we may want to revive it at some point for self-service key creation
> CAS-36 Remove token from admin page

- .github/actions/docker-deploy/action.yml
- .github/actions/integration-tests/action.yml
- .github/actions/vector-search-index-deploy/action.yml
- .github/actions/vector-search-index-undeploy/action.yml
- .github/workflows/integration-test-workflow.yml
Quick summary of the process:
1. Builds the docker image for cellarium-cloud for the specified version
2. Deploys the model service
3. Deploys the API service
4. If user set `deploy-index` to `true`, deploys the specified vector search index
5. Checks out the specified version of cellarium-cas and runs integration tests (currently just the one that was already there)
6. If user set `deploy-index` to `true`, undeploys the specified vector search index
A couple points that warrant further discussion for this PR:
1. When you run the gcloud commands to deploy/undeploy an index, it kicks off the operation and returns immediately.  For the deploy operation, it gives you an operation ID that I am checking repeatedly so it stays on that step until the deploy is complete.  However, undeploy …
> Created a workflow for spinning up a test server and running integration tests against it

- .github/workflows/integration-test-workflow.yml
- requirements.txt
- src/casp/services/_settings.py
- src/casp/services/db/__init__.py
- src/casp/services/deploy/Dockerfile.ns.pytorch
- src/casp/services/deploy/Dockerfile.ns.pytorch_cuda
- src/casp/services/deploy/Dockerfile.pytorch
- src/casp/services/deploy/Dockerfile.pytorch_cuda
...also make it so we could log queries in prod if we have to
*Note*: this required upgrading a fair number of components:
- pg8000 (to support socket connections)
- The pytorch image to 2.0.1
- Python to 3.11.4 (via the pytorch image)
- smart-open (seemed to be causing issues initializing)
I also needed to make the initialization of the db session maker to the first connection attempt since it requires google creds and we don't want to require that for unit tests.
Also Note:
I ran the integration tests to verify (woo!) but did have to change to make it deploy the admin service so that the DB would migrate (that caused a failure initially).  Some day we should decouple that but not today.
> CAS-43 Bump the version of the cloud sql connector

- src/casp/services/_settings.py
- src/casp/services/admin/templates/email/new_key.html
- src/casp/services/admin/templates/email/welcome.html
- src/casp/services/admin/templates/email/welcome.txt
What it says on the tin.  I updated the config in prod but I wanted to have the default reflect the working value.  Also updates the pip install to not install from github
> CAS-44 Update default email sender and update email with correct pip install

- requirements.txt
- src/casp/services/admin/views.py
- src/casp/services/api/services/consensus_engine/strategies.py
- src/casp/services/db/migrations/versions/t_2024-06-27_21-00-54_update_cell_related_models_before_new_.py
- src/casp/services/db/models/cells.py
- src/casp/services/model_inference/services.py
Updates:
* Add dataset_version_id to ingest info table
* Drop not null constraints from `obs_metadata_extra` and `original_cell_id` as for the current extract they are not necessary.
* Since in new data we now have "unknown" cell type instead of "naive cell" we have to handle this in ontology aware strategy
> Feat: Update cell related models

- requirements.txt
- src/casp/services/db/__init__.py
This PR makes us create DB connections as needed as opposed to eagerly.  Managing connections eagerly seems to cause credential expiration errors - they are innocuous since the connection gets recreated but it spams our logs.  I've tested on my environment and it seems to make the exceptions disappear.
> CAS-58 Fix Sentry Error Spam

- src/casp/services/constants.py
Enforcing all clients to update to version 1.5.1, as it includes the newer ontology. Version 1.4.13 does not include it because I mistakenly tagged the wrong commit on a client while trying to release 1.4.13.
Please refer to [this PR](https://github.com/cellarium-ai/cellarium-cas/pull/83) on the client repo for more details.
> Chore: Update min client version to 1.5.1

- src/casp/services/admin/views.py
- src/casp/services/db/models/users.py
For datetime columns on the user and user activity tables, we were setting the default to the result of calling datetime.now() once.  So it was basically only calling it the first time it checked for the default value and then only ever calling it again in new instances of the server (I think).  This resulted in a bunch of incorrect datetime values.  I've fixed it by replacing it with a lambda that calls datetime.now() each time a new user or user activity object is instantiated.
> Fix for the timestamp bug
